<?php
/**
 * Created by PhpStorm.
 * User: 時間在說謊
 * Date: 2018/6/2
 * Time: 14:17
 */

namespace app\admin\controller;

use think\Controller;

class Basic extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    // 验证权限方法
    public function check_auth()
    {
        // 当前用户所在分组
        $where_access['uid'] = '1';
        $info = db('admin_group_access')->where($where_access)->find();
        // 分组信息
        $where_group['group_id'] = $info['group_id'];
        $group_info = db('admin_group')->where($where_group)->find();
        // 分组对应的权限
        $rules = $group_info['rules'];
        $auth = explode(',',$rules);
        // 模块
        $module = request()->module();
        // 控制器
        $controller = request()->controller();
        // 方法
        $action = request()->action();
        // 路由地址
        $url = $module . '/' . $controller . '/' . $action;
        // 路由地址对应的id
        $rule = db('admin_auth_rule')->where(['match_rule'=>$url])->find();
        if (!in_array($rule['id'],$auth)) {
            exit("<script>alert('您没有权限操作');window.history.go(-1);</script>");
        }
    }
}