<?php
/**
 * Created by PhpStorm.
 * User: 時間在說謊
 * Date: 2018/6/2
 * Time: 14:16
 */

namespace app\admin\controller;

class Merchant extends Basic
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

//        $this->check_auth();
    }

    /**
     * 渲染商家列表展示
     * Created by liuHW
     * Date 2018/6/13
     */
    public function merchant_list()
    {
        return view();
    }

}