<?php
/**
 * Created by PhpStorm.
 * User: 時間在說謊
 * Date: 2018/7/28
 * Time: 14:47
 */

namespace app\api\controller;

use think\Controller;

class Basic extends Controller {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 返回统一的 json 信息
     * @param string $message       文字描述
     * @param array  $data          数组
     * @param string $error_code    错误编码
     * @param int    $total_page    分页总数
     * @return string
     * Created by liuHW
     * Date 2018/10/17
     */
    public function create_json_info($message = null, $data = null, $error_code = null, $total_page = null)
    {
        $results = [];
        $results['flag'] = 'success';
        $results['message'] = $message;
        $results['error_code'] = $error_code ? $error_code : '0000';
        $results['data'] = $data;
        if($total_page) {
            $results['total_page'] = $total_page;
        }
        // 返回 JSON 数据格式到客户端 包含状态信息
        header('Content-Type:application/json; charset=utf-8');
        exit(json_encode($results));
    }
}